### ISSUE TITLE
How To Work It?

### ISSUE THREAD

**Issue by MrMonday22** [ryan-schroeder/sonic-candle#5]
How Do You Open Up Sonic Candle, Or Find The File To Open It? I Figure Out How To Open Sonic Candle

**Comment by ryan-schroeder** [comment]
Hi!  After you download it from here: https://sourceforge.net/projects/soniccandle/files/latest/download  you should get a "jar" file; sonic-candle-1.1.11.jar .  Clicking that file should open the program; make sure you also have java installed on your computer (https://www.java.com/en/)  =)

**Comment by MrMonday22** [comment]
Alright, Thx Man!!!

**Comment by PandainParadise** [comment]
What size image should I upload? Because it always comes out blurry :/

**Comment by MrMonday22** [comment]
What size of photo have you been trying to use? I usually try to use like
background photos

**Comment by PandainParadise** [comment]
I just use random photos on the internet, but I've been trying ones that fit my computer. (4608 x 3456)

**Comment by ThunderDoofus** [comment]
Hi guys when i download the latest version of sonic candle it give's me a rar file but inside it there is no application what can i do to fix this?

**Comment by Dakkra** [comment]
Hello,The file downloaded should be a JAR (Java archive) file. To run it you need to have Java installed on your computer. You may need to add Java to your system PATH or run "java -jar [filename.jar]" in the command line where the JAR file is stored.CFR: https://www.java.com/en/download/help/download_options.xmlHope this helps,Chris Soderquist (Dakkra)On May 20, 2018 3:51 AM, ThunderDoofus <notifications@github.com> wrote:Hi guys when i download the latest version it give's me a rar file but inside it there is no application what can i do to fix this?

**Comment by Fab77b** [comment]
Hello Dakkra,
I can't manage to install SonicCandle. Where am I wrong ?
1- I installed the last version of Java (I'm on a portable computer, with Windows 10)
2- I downloaded SonicCandle, double-clicked (tried with right-click / open with "Java(TM) Platform Se Binary
All I get is a quick window "command-like", in which I can't read anything because it disappears as soon as it appeared...
Anybody help ? Some problems with last version of Java maybe ?
Thanks in advance
