### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Kubek0212** [ryan-schroeder/sonic-candle#6]
While previous tracks were rendered perfectly fine, on my lastest attempt this window pops up on the beggining of process. Have You got any ideas what should I do?
EDIT: nevermind, the DAV's (LMMS) export settings after update were changed, but after trying everything video has bad audio quality

![scerror](https://user-images.githubusercontent.com/33349024/33852867-4841dbc0-debc-11e7-927a-0cc51fcad401.png)

P.S. Rendering (30MB) .wav to .mp4
P.P.S. I haven't seen and update for a quite long time. Is Sonic Candle still in development?

**Comment by Dakkra** [comment]
Hello!

Sorry for the very delayed reply. Sonic Candle is not currently in active development due to real life priorities for both Ryan and myself. 

The audio quality was a known issue on my part. The encoder we were using didn't favor audio quality (low bitrate) and was not our preferred method. We generally preferred to use the image-sequence render and considered the video output as a convenience. Someday we plan on updating the encoder (by either making our own or interfacing ffmpeg into the application) but we have no ETA and it's not very high on our list of worries.

Thanks for your interest in Sonic Candle,
Dakkra
